"use strict";

const V1_CONTROL_CONTEXT_BASELINE_CHARS = 48000;
const LEAN_CONTROL_CONTEXT_MAX_RATIO = 0.25;
const LEAN_CONTROL_CONTEXT_MAX_CHARS = V1_CONTROL_CONTEXT_BASELINE_CHARS * LEAN_CONTROL_CONTEXT_MAX_RATIO;
const MAX_CONTEXT_RESULTS = 100;
const DEFAULT_CONTEXT_RESULTS = 10;
const MAX_RELATIONS_PER_RESULT = 100;
const DEFAULT_RELATIONS_PER_RESULT = 40;

module.exports = {
  DEFAULT_CONTEXT_RESULTS,
  DEFAULT_RELATIONS_PER_RESULT,
  LEAN_CONTROL_CONTEXT_MAX_CHARS,
  LEAN_CONTROL_CONTEXT_MAX_RATIO,
  MAX_CONTEXT_RESULTS,
  MAX_RELATIONS_PER_RESULT,
  V1_CONTROL_CONTEXT_BASELINE_CHARS
};
